# This is a basic workflow to help you get started with Actions

name: Run a LuaUnit Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Install lua and prepare github actions for running LUA scripts
    #- name: Install Lua/LuaJIT
   - uses: leafo/gh-actions-lua@v3
     with:
       luaVersion: ${{ matrix.luaVersion }}

    # Runs a set of commands using the runners shell
    - name: Attempt to run a lua script
      run: lua helloworld.lua
